### ISSUE TITLE
Burn typology

### ISSUE THREAD

**Issue by aellenhicks** [OGMS/ogms#93] opened 2015-08-05 15:26 UTC
This issue was originally posted on the googlecode site.  I received a response that this request is outside of the domain of OGMS, but I am looking for suggestions for which ontology to request these terms in.  I was directed here

original post:
We are representing 'burn patient role' in OMRSE.  The definition is, 'a patient role that inheres in an organism suffering a thermal, electrical, chemical or radiation burn.'

We are using OGMS 'injury' to represent a 'injured patient role', and we would like to use burns analogously.

We request the following hierarchy of terms under 'injury':
'burn'
     'thermal burn'
     'electrical burn'
     'chemical burn'
     'radiation burn'

**Comment by dillerm** [comment] 2016-04-01 16:47
I'd like to propose a definition for 'burn'; however, before doing, I'd like to offer a brief explanation of each burn subtype.

- thermal burn - tissue damage caused by an increase in temperature beyond the normal limits of the body, in which the internal kinetic energy of a system is transferred (i.e., heat transfer) to an organism causing structural damage to proteins. This does not include burns caused by heat exposure from an electrical current. (Vehicle = molecules, atoms, and/or electrons)
- electrical burn - tissue damage caused by exposure to electrical currents whose voltage, flow of electric charge, resistance, and/or frequency are beyond the normal limits of the body, which lead to structural damage to plasma membranes and the proteins therein. (Vehicle = electrons and/or other ions)
- radiation burn - tissue damage caused by electromagnetic waves interacting with the physical components of tissue in a way that induces damaging chemical responses. (Vehicle = photons)
- chemical burn - tissue damage caused by direct contact with a corrosive substance. 

As you might see, each of these burns involves a supraphysiological change that is the result of a physical interaction between an organism and some instance of a material entity (e.g., an electron, photon, corrosive substance, etc.). This material entity is exogenous to the body and has some disposition to induce bodily harm. As such, my proposed definition for 'burn' is: 

"An injury caused by some pathological transformation that has as participant some material entity which is the bearer of some disposition to induce bodily harm upon direct contact with the tissue of an organism."

**Comment by mark-jensen** [comment] 2016-04-20 01:58
> I received a response that this request is outside of the domain of OGMS, but I am looking for suggestions for which ontology to request these terms in. I was directed here

I also agree that specific types of injuries don't belong in OGMS. Just as it isn't the place for typologies of diseases or syndromes, etc. But until some enterprising folks take the initiative to create an injury ontology, perhaps OGMS can act as an incubator for terms like these. I will propose it on the next developers call.

**Comment by BAevermann** [comment] 2017-12-28 01:12
Closed ticket because issue has not been acted upon in reasonable amount of time.

**Closed by BAevermann** 2017-12-28 01:12 UTC
